"""empty message

Revision ID: 1749c483403c
Revises: bdca318cf71e
Create Date: 2026-02-26 04:07:34.657412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1749c483403c'
down_revision = 'bdca318cf71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', sa.Text(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('attachments')

    # ### end Alembic commands ###
