"""empty message

Revision ID: 18a788c2f185
Revises: 529fda599738
Create Date: 2026-06-22 00:41:58.258021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a788c2f185'
down_revision = '529fda599738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('meeting_supervisor_id', 'supervisor', ['supervisor_id'], ['sid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supervisor_id')

    # ### end Alembic commands ###
