"""empty message

Revision ID: 2060f3c4ab33
Revises: 42d0cc776f4e
Create Date: 2026-05-04 18:15:13.317796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2060f3c4ab33'
down_revision = '42d0cc776f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('doctor',
               existing_type=sa.TEXT(length=200),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('assistent',
               existing_type=sa.TEXT(length=200),
               type_=sa.Integer(),
               nullable=True)
        batch_op.create_foreign_key('fk_project_doctor', 'supervisor', ['doctor'], ['sid'])
        batch_op.create_foreign_key('fk_project_assistant', 'supervisor', ['assistent'], ['sid'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.TEXT(length=200), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('assistent',
               existing_type=sa.Integer(),
               type_=sa.TEXT(length=200),
               nullable=True)
        batch_op.alter_column('doctor',
               existing_type=sa.Integer(),
               type_=sa.TEXT(length=200),
               nullable=True)

    # ### end Alembic commands ###
