"""empty message

Revision ID: 301fbb8fb678
Revises: b53839d99489
Create Date: 2026-06-16 22:25:46.213409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301fbb8fb678'
down_revision = 'b53839d99489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_without_team', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('selected_members', sa.Text(), nullable=True))

    with op.batch_alter_table('supervisor_notification', schema=None) as batch_op:
        batch_op.alter_column('nid',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_notification', schema=None) as batch_op:
        batch_op.alter_column('nid',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('selected_members')
        batch_op.drop_column('publish_without_team')

    # ### end Alembic commands ###
