"""empty message

Revision ID: 42d0cc776f4e
Revises: 6b564b243828
Create Date: 2026-04-25 13:31:51.074043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d0cc776f4e'
down_revision = '6b564b243828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_project',
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.sid'], ),
    sa.PrimaryKeyConstraint('supervisor_id', 'project_id')
    )
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.drop_column('teams')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teams', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('supervisor_project')
    # ### end Alembic commands ###
