"""empty message

Revision ID: 451b69afe90d
Revises: b53839d99489
Create Date: 2026-06-16 20:17:26.024877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451b69afe90d'
down_revision = 'b53839d99489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_supervisor_notification')
    with op.batch_alter_table('supervisor_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('supervisor_notification_project_id', 'project', ['project_id'], ['pid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    op.create_table('_alembic_tmp_supervisor_notification',
    sa.Column('nid', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('_from_id', sa.INTEGER(), nullable=True),
    sa.Column('_from_name', sa.VARCHAR(), nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), nullable=False),
    sa.Column('read', sa.BOOLEAN(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], name=op.f('sup_notification_project_id')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.sid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    # ### end Alembic commands ###
