"""empty message

Revision ID: 460edfbae08c
Revises: d1a11d87d16e
Create Date: 2026-05-30 22:37:45.400342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460edfbae08c'
down_revision = 'd1a11d87d16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.Text(), nullable=True))

    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.drop_column('github_url')
        batch_op.drop_column('linkedin_url')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('github_url')
        batch_op.drop_column('linkedin_url')

    # ### end Alembic commands ###
