"""empty message

Revision ID: 529fda599738
Revises: a43808c84353
Create Date: 2026-06-21 13:20:25.208254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529fda599738'
down_revision = 'a43808c84353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_note', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('proof_link', sa.Text(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('proof_link')
        batch_op.drop_column('proof_note')

    # ### end Alembic commands ###
