"""empty message

Revision ID: 564948db82c0
Revises: c86fc420bfee
Create Date: 2026-06-11 01:00:17.750501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564948db82c0'
down_revision = 'c86fc420bfee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('supervisor_id_meeting', 'supervisor', ['supervisor'], ['sid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint('supervisor_id_meeting', type_='foreignkey')
        batch_op.drop_column('supervisor')

    # ### end Alembic commands ###
