"""empty message

Revision ID: 5dcbfa0d401c
Revises: be3ce18e5140
Create Date: 2026-05-15 02:10:22.816457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcbfa0d401c'
down_revision = 'be3ce18e5140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projects_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.drop_column('projects_limit')

    # ### end Alembic commands ###
