"""empty message

Revision ID: 6ac3d041ab5f
Revises: 2060f3c4ab33
Create Date: 2026-05-05 16:29:40.227214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac3d041ab5f'
down_revision = '2060f3c4ab33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(length=200), nullable=True),
    sa.Column('notes', sa.Text(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(length=200), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting')
    # ### end Alembic commands ###
