"""empty message

Revision ID: 6b564b243828
Revises: 
Create Date: 2026-04-22 15:42:31.419411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b564b243828'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(length=200), nullable=False),
    sa.Column('description', sa.Text(length=200), nullable=False),
    sa.Column('year', sa.Text(length=200), nullable=False),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('statue', sa.Text(length=200), nullable=True),
    sa.Column('doctor', sa.Text(length=200), nullable=True),
    sa.Column('assistent', sa.Text(length=200), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=False),
    sa.Column('team_members', sa.Text(length=200), nullable=True),
    sa.Column('attachments', sa.Text(length=200), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('supervisor',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('teams', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('person',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('in_team', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('supervisor_notification',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('_from_id', sa.Integer(), nullable=True),
    sa.Column('_from_name', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.sid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('notification',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('_from_id', sa.Integer(), nullable=True),
    sa.Column('_from_name', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['person.pid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('task',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(length=200), nullable=False),
    sa.Column('project_id', sa.Text(length=200), nullable=True),
    sa.Column('assigned_to', sa.Text(length=200), nullable=True),
    sa.Column('status', sa.Text(length=10), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['person.pid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('notification')
    op.drop_table('supervisor_notification')
    op.drop_table('person')
    op.drop_table('supervisor')
    op.drop_table('project')
    # ### end Alembic commands ###
