"""empty message

Revision ID: 751b6750c7c1
Revises: 564948db82c0
Create Date: 2026-06-11 01:08:40.954928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751b6750c7c1'
down_revision = '564948db82c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('supervisor_id_meeting'), type_='foreignkey')
        batch_op.drop_column('supervisor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('supervisor_id_meeting'), 'supervisor', ['supervisor'], ['sid'])

    # ### end Alembic commands ###
