"""empty message

Revision ID: 8417b10b3f3f
Revises: 1749c483403c
Create Date: 2026-02-27 06:25:21.040081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8417b10b3f3f'
down_revision = '1749c483403c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_notification',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('_from_id', sa.Integer(), nullable=True),
    sa.Column('_from_name', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.did'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('specialty_level')
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('specialty_level', sa.INTEGER(), nullable=True))

    op.drop_table('supervisor_notification')
    # ### end Alembic commands ###
