"""empty message

Revision ID: 85cefc283095
Revises: 87719de2229f
Create Date: 2026-05-20 21:29:14.424416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cefc283095'
down_revision = '87719de2229f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.TEXT(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.TEXT(length=200),
               nullable=False)

    # ### end Alembic commands ###
