"""empty message

Revision ID: 87719de2229f
Revises: 5dcbfa0d401c
Create Date: 2026-05-19 00:21:55.917791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87719de2229f'
down_revision = '5dcbfa0d401c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(length=200), nullable=False),
    sa.Column('message_type', sa.Text(length=200), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.sid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
