"""empty message

Revision ID: 9667e0d25bb8
Revises: dec827c30659
Create Date: 2026-06-16 17:22:38.236460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9667e0d25bb8'
down_revision = 'dec827c30659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(length=200), nullable=True))
        batch_op.drop_column('statue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statue', sa.TEXT(length=200), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
