"""empty message

Revision ID: ac1b7fbcf0f8
Revises: 
Create Date: 2026-06-22 05:06:04.692051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1b7fbcf0f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('projects_limit', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('project',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(length=200), nullable=False),
    sa.Column('description', sa.Text(length=200), nullable=False),
    sa.Column('year', sa.Text(length=200), nullable=False),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(length=200), nullable=True),
    sa.Column('doctor', sa.Integer(), nullable=True),
    sa.Column('assistent', sa.Integer(), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=False),
    sa.Column('team_members', sa.Text(length=200), nullable=True),
    sa.Column('attachments', sa.Text(length=200), nullable=True),
    sa.Column('similar_ideas', sa.Text(), nullable=True),
    sa.Column('special', sa.Boolean(), nullable=True),
    sa.Column('under_review', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('intended_team_size', sa.Integer(), nullable=True),
    sa.Column('publish_without_team', sa.Boolean(), nullable=True),
    sa.Column('selected_members', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assistent'], ['supervisor.sid'], ),
    sa.ForeignKeyConstraint(['doctor'], ['supervisor.sid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('discussion',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('supervisors', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('meeting',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(length=200), nullable=True),
    sa.Column('notes', sa.Text(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(length=200), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.sid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('message',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(length=200), nullable=False),
    sa.Column('message_type', sa.Text(length=200), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.sid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('person',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('in_team', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('first_discussion_result', sa.Integer(), nullable=True),
    sa.Column('finel_project_degree', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('supervisor_notification',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('_from_id', sa.Integer(), nullable=True),
    sa.Column('_from_name', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.sid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('supervisor_project',
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.sid'], ),
    sa.PrimaryKeyConstraint('supervisor_id', 'project_id')
    )
    op.create_table('notification',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('_from_id', sa.Integer(), nullable=True),
    sa.Column('_from_name', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.ForeignKeyConstraint(['student_id'], ['person.pid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('task',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(length=200), nullable=False),
    sa.Column('project_id', sa.Text(length=200), nullable=True),
    sa.Column('status', sa.Text(length=10), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(length=200), nullable=True),
    sa.Column('proof_note', sa.Text(length=200), nullable=True),
    sa.Column('proof_link', sa.Text(length=200), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['person.pid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('notification')
    op.drop_table('supervisor_project')
    op.drop_table('supervisor_notification')
    op.drop_table('person')
    op.drop_table('message')
    op.drop_table('meeting')
    op.drop_table('discussion')
    op.drop_table('project')
    op.drop_table('supervisor')
    # ### end Alembic commands ###
