"""empty message

Revision ID: bdca318cf71e
Revises: 
Create Date: 2026-01-21 04:13:24.648705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdca318cf71e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(length=200), nullable=False),
    sa.Column('description', sa.Text(length=200), nullable=False),
    sa.Column('year', sa.Text(length=200), nullable=False),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('statue', sa.Text(length=200), nullable=True),
    sa.Column('doctor', sa.Text(length=200), nullable=True),
    sa.Column('assistent', sa.Text(length=200), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=False),
    sa.Column('team_members', sa.Text(length=200), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('supervisor',
    sa.Column('did', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(length=200), nullable=False),
    sa.Column('email', sa.Text(length=200), nullable=False),
    sa.Column('phone', sa.Text(length=200), nullable=False),
    sa.Column('specialties', sa.Text(length=200), nullable=False),
    sa.Column('department', sa.Text(length=10), nullable=True),
    sa.Column('role', sa.Text(length=10), nullable=False),
    sa.Column('projects', sa.Text(length=200), nullable=True),
    sa.Column('password', sa.Text(length=200), nullable=False),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('person',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('specialty_level', sa.Integer(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('in_team', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('notification',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('_from_id', sa.Integer(), nullable=True),
    sa.Column('_from_name', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['person.pid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('task',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(length=200), nullable=False),
    sa.Column('project_id', sa.Text(length=200), nullable=True),
    sa.Column('assigned_to', sa.Text(length=200), nullable=True),
    sa.Column('status', sa.Text(length=10), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['person.pid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('notification')
    op.drop_table('person')
    op.drop_table('supervisor')
    op.drop_table('project')
    # ### end Alembic commands ###
