"""empty message

Revision ID: bf964e437f30
Revises: ac1b7fbcf0f8
Create Date: 2026-07-04 22:54:18.187485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf964e437f30'
down_revision = 'ac1b7fbcf0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.Text(), nullable=True))
        batch_op.drop_column('specialties')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialties', sa.TEXT(), nullable=True))
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###
