"""empty message

Revision ID: d5951c5a19ae
Revises: 7e779264191c
Create Date: 2026-06-15 19:07:11.357338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5951c5a19ae'
down_revision = '7e779264191c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('under_review', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('completed')
        batch_op.drop_column('under_review')

    # ### end Alembic commands ###
