"""empty message

Revision ID: dec827c30659
Revises: 7f2059d93130
Create Date: 2026-06-16 15:41:59.165297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec827c30659'
down_revision = '7f2059d93130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.TEXT(length=200), nullable=True))

    # ### end Alembic commands ###
