"""empty message

Revision ID: f383a6803a93
Revises: feed2c03e905
Create Date: 2026-05-26 03:53:03.416057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f383a6803a93'
down_revision = 'feed2c03e905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notification_sender'), type_='foreignkey')

    with op.batch_alter_table('supervisor_notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notification_sender'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_notification', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_notification_sender'), 'person', ['_from_id'], ['pid'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_notification_sender'), 'person', ['_from_id'], ['pid'])

    # ### end Alembic commands ###
