"""empty message

Revision ID: fbdc198c74dc
Revises: 5aaffb2fc59d
Create Date: 2026-06-20 16:57:05.339504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdc198c74dc'
down_revision = '5aaffb2fc59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.alter_column('supervisors',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.alter_column('supervisors',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
