"""empty message

Revision ID: feed2c03e905
Revises: 85cefc283095
Create Date: 2026-05-23 23:39:18.151479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feed2c03e905'
down_revision = '85cefc283095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_notification_sender', 'person', ['_from_id'], ['pid'])

    with op.batch_alter_table('supervisor_notification', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_notification_sender', 'person', ['_from_id'], ['pid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
